//
//  carousel-domain-configuration.swift
//  carousel
//
//  Created by Shaheen Ghiassy on 10/1/17.
//

import UIKit

/**
 *
 *
 *      THIS IS AN AUTOGENERATED CLASS
 *
 *      DO NOT MANUALLY EDIT
 *
 *
 */


public class carousel_domain_configuration: NSObject {

    public let domain = "carousel.groupon.com"
    
    func homepage() -> UIViewController {
        return CarouselViewController()
    }
    
}
